config/routes.rb
Rails.application.routes.draw do
  root 'to_dos#index'
  
  resources :to_dos
  get 'to_dos/:id/finish', to: 'to_dos#finish', as: :finish_to_do
end

app/models/to_do.rb
class ToDo
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :deadline, type: String
  field :finished_at, type: String
  field :status, type: Symbol, default: :pending
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: [:edit, :update, :destroy, :finish]

  def new
    @to_do = ToDo.new
  end

  def create
    @to_do = ToDo.new(to_do_params)

    respond_to do |format|
     if @to_do.save
        format.html { redirect_to to_dos_path, notice: 'Tarefa criada com sucesso.' }
        format.json { render :show, status: :created, location: @to_do }
        else
          format.html { render :new }
          format.json { render json: @to_do.errors, status: :unprocessable_entity }
        end
    end
  end

  def update
      
        if @to_do.update(to_do_params)
          redirect_to to_dos_path, notice: 'Tarefa atualizada com sucesso.'
        else
          render :edit
        end
  end
  
  def finish
    @to_do.status = :finished
    @to_do.finished_at = Date.today.strftime("%m/%d/%Y")
    
    if @to_do.save
      redirect_to to_dos_path      
    else    
      redirect_to to_dos_path, alert: 'Não foi possível finalizar tarefa.'      
    end
  end

  def destroy
    @to_do.destroy
    
    redirect_to to_dos_url
  end

  private
    def set_to_do
      @to_do = ToDo.find(params[:id])
    end

      def to_do_params
        params.require(:to_do).permit(:title, :description, :deadline, :finished_at)            
      end
      
      
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | Tarefas
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Tarefas
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Tarefas", root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              a href=root_path
                | Home
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = msg
      = yield

app/views/to_dos/_form.html.slim
= form_for @to_do do |f|
  - if @to_do.errors.any?
    #error_explanation
      h2 = "#{pluralize(@to_do.errors.count, "error")}"
      ul
        - @to_do.errors.full_messages.each do |message|
          li = message

  .field.form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
    
    
    
    
  
  .field.form-group
    = f.label :deadline
    = f.text_field :deadline, class: 'form-control'
    
  .field.form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .actions
    = f.submit 'Salvar', class: 'btn btn-primary'

app/views/to_dos/edit.html.slim
h1 Editando tarefa

== render 'form'

app/views/to_dos/index.html.slim
h1 Tarefas

table.table.table-striped
  thead
    tr
      th Título
      th Descrição
      th Prazo
      th Finalizado em
      th Status
      th
      th
      th

  tbody
    - ToDo.all.each do |to_do|
      tr
        td = to_do.title
        td = to_do.description
        td = to_do.deadline
        td = to_do.finished_at
        - if to_do.status == :pending
          td
            span.label.label-default = t to_do.status
        - elsif to_do.status == :finished
          td
            span.label.label-success = t to_do.status
        
        td = link_to 'Marcar como feito', finish_to_do_path(to_do), class: 'btn btn-xs btn-primary'
        td = link_to 'Editar', edit_to_do_path(to_do)
        td = link_to 'Apagar', to_do, data: { confirm: 'Você tem certeza?' }, method: :delete

br

= link_to 'Adicionar novo', new_to_do_path, class: 'btn btn-primary'

app/views/to_dos/new.html.slim
h1 Nova tarefa

== render 'form'